# Create a configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: apl-pagamentos-config
  labels:
    app: apl-pagamentos
data:
  DATASOURCE_INITIALIZE: 'true'
  HIBERNATE_DDL_AUTO: update
  PEDIDO_URL: http://acd652e434c7140808cb5801d25eea90-928075136.us-east-1.elb.amazonaws.com:9091/tech-challenge/pedidos
  MONGO_URI: mongodb+srv://usertemp:xM9HCOM8vhRPSW93@fiap-cluster.2quggum.mongodb.net/?retryWrites=true&w=majority
  MONGO_DATABASE: fiap_pagamento
  QUEUE_NOTIFICA_CLIENTE: ClientNotify
  QUEUE_ATUALIZA_PEDIDO: StatusChange
  SERVLET_CONTEXT_PATH: /tech-challenge/pagamento
